name: ficbatch
description: "AO3 browser and reader."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  html: ^0.15.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.1.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  webview_windows: ^0.4.0
  path_provider: ^2.1.2
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
